export enum MainEnum {
  APP_TOKEN = "SYNERIS_QC_TOKEN",
  USER_NAME = "SYNERIS_QC_USER_NAME",
  USER_ID = "SYNERIS_QC_USER_ID",
  ROLE_NAME = "SYNERIS_QC_ROLE_NAME",
  ROLE_ID = "SYNERIS_QC_ROLE_ID",
  EMPLOYEE_ID = "SYNERIS_QC_EMPLOYEE_ID",
  ACCESS_ARRAY = "SYNERIS_QC_ACCESS_ARRAY",
}
